// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzD1Gh8i8s3-ageHuxRVDc1qH5hJDng0',
    appId: '1:510887295011:web:9a2c27ce848d526f7dd996',
    messagingSenderId: '510887295011',
    projectId: 'learn-game-project',
    authDomain: 'learn-game-project.firebaseapp.com',
    storageBucket: 'learn-game-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6AsVpZZJogj1YN_v2PQQb781uS0SzsvA',
    appId: '1:510887295011:android:ecd4632dbc1473c57dd996',
    messagingSenderId: '510887295011',
    projectId: 'learn-game-project',
    storageBucket: 'learn-game-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxUKtkjN6wP81UyhRUOmttjFtDbcXNyM',
    appId: '1:510887295011:ios:0426aa8e504f86757dd996',
    messagingSenderId: '510887295011',
    projectId: 'learn-game-project',
    storageBucket: 'learn-game-project.firebasestorage.app',
    iosBundleId: 'com.example.learnGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxUKtkjN6wP81UyhRUOmttjFtDbcXNyM',
    appId: '1:510887295011:ios:0426aa8e504f86757dd996',
    messagingSenderId: '510887295011',
    projectId: 'learn-game-project',
    storageBucket: 'learn-game-project.firebasestorage.app',
    iosBundleId: 'com.example.learnGame',
  );
}
